### ISSUE TITLE
GSP/ECR 2024 Website updates - Menu navigation changes

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#606] opened 2024-02-08 21:46 UTC
- [x] Change the following top level menu navigation titles:

1. About > About Us
2. Community > Partner with Us
3. Resources > News & Impact

For each of the top-level titles, the drop down items are as follows:

- [x] About Us
1. Our Story
2. Team
3. Advisory
5. Diversity, Equity, and Inclusion
6. Data Use Policy
7. Contact Us

- [x] Products 
1. Data Portal
2. Submission Portal
3. NMDC EDGE

- [x] Resources
1. Data
2. Bioinformatics Workflows
3. GitHub (direct link to https://github.com/microbiomedata)
4. Documentation
5. Data Management

- [x] Partner with Us
1. Community
2. Ambassadors
3. Champions
4. User Research
5. Events

- [ ] News & Impact
1. Press Room
2. Newsletters
3. Annual Reports
4. Publications

**Comment by ssarrafan** [comment] 2024-02-08 22:03
For “About” and “Community” there are overview pages, whereas “Products” and “Resources” do not have separate overview pages. Can the “About” and “Community” have those overview pages listed in the dropdown so it’s more apparent where to get that information? 

- “About” page should be renamed to “Our Story” 

- “Community” page should be renamed to “Partner with Us” 

Under Resources, add two new pages for Documentation & link to GH

- For Documentation, will create a new page that describes our documentation and also how we handle translating user guides for NMDC EDGE 

_Under About, should we rename any of the pages to make them more descriptive? Might not be clear what ‘FAIR; metadata; or workflows’ pages actually are
Does FAIR need to be called out in the main menu or can it just be linked to from other pages?
Can remove ‘NMDC Snapshots’ from main menu, can just link to it from Ambassador page
Can archive/remove Community Conversations page from main menu, can move the content somewhere else_

**Comment by shreddd** [comment] 2024-02-09 21:13
What does the "Data" link point to under Resources? If this is the data portal then we already have it under products.

**Comment by eecavanna** [comment] 2024-02-22 00:33
I'm working on this now.

**Comment by eecavanna** [comment] 2024-02-22 00:50
Before I make changes to the menu, here's a composition of screenshots showing its initial state:

![nmdc-website-original-menu](https://github.com/microbiomedata/issues/assets/134325062/1396e008-a73d-407a-b459-104f03268bf5)

**Comment by eecavanna** [comment] 2024-02-22 01:06
Here's what the new top-level menu items look like:

![image](https://github.com/microbiomedata/issues/assets/134325062/48c53791-2bb8-4807-b177-435c8a1c2f49)

**Comment by eecavanna** [comment] 2024-02-22 01:18
I did not make any changes to the "Products" menu.

![image](https://github.com/microbiomedata/issues/assets/134325062/c33af6fb-077e-48db-964e-236d28dbf927)

**Comment by eecavanna** [comment] 2024-02-22 01:27
> What does the "Data" link point to under Resources?

I have the same question. @ssarrafan and @jkelliher-github, do either of you know?

One of the changes I made to the "About Us" menu as part of this ticket was that I removed the menu item labeled "Metadata" from the "About" menu. I didn't write down where that menu item pointed (I can spin up an old backup of the website locally to check, but I won't do that if not necessary). I wonder whether the page that menu item pointed to, is the page they had in mind for this new "Data" menu item.

**Comment by eecavanna** [comment] 2024-02-22 01:39
Here's what I did to the "Resources" menu (after creating it):

- Added a menu item labeled "Bioinformatics Workflows" that links to https://microbiomedata.org/workflows/
- Added a menu item labeled "GitHub" that links to https://github.com/microbiomedata
- Added a menu item labeled "Documentation" that links to https://nmdc-documentation.readthedocs.io/
- Added a menu item labeled "Data Management" that links to https://microbiomedata.org/data-management/

![image](https://github.com/microbiomedata/issues/assets/134325062/0572909c-9122-4c97-89de-2d43ab14888c)

⚠️ **TODO:** Add a menu item labeled "Data", once I know what people want it to link to.

**Comment by eecavanna** [comment] 2024-02-22 01:50
Here's what I did to the "Partner with Us" menu (after renaming it from "Community"):

- Added a link labeled "Community" that links to https://microbiomedata.org/community/
- Removed the link labeled "NMDC Snapshots"
- Removed the link labeled "Community Conversations"
- Updated the menu item labeled "News and Events" to be labeled "Events"

Here's what it looks like now:

![image](https://github.com/microbiomedata/issues/assets/134325062/932c93b1-9fab-424d-a8b1-c6cad42739fe)

**Comment by eecavanna** [comment] 2024-02-22 01:59
Here's what I did to the "News & Impact" menu (after renaming it from "Resources"):

- Removed the menu item labeled "Data Management"
- Updated the menu item labeled "Media Materials" to be labeled "Press Room"
  - Then, moved that "Press Room" menu item to the top of the menu

Here's what it looks like now:

![image](https://github.com/microbiomedata/issues/assets/134325062/7aa13438-4c98-4e91-b772-9d2199073b55)

⚠️ **TODO**: Add a menu item labeled "Newsletters" that people can click on to access past NMDC newsletters. I don't know how I can do that yet.

**Comment by eecavanna** [comment] 2024-02-22 02:02
### Status summary

All of the changes listed in the Issue description have been made; except those listed below:
- [ ] I did not add a menu item labeled "Data" to the "Resources" menu. That's because I don't know yet what anyone wants it to link to.
- [ ] I did not add a menu item named "Newsletters" to the "News & Impact" menu. That's because I don't know yet how people can access a list of previous NMDC newsletters.

**Comment by ssarrafan** [comment] 2024-02-23 23:59
@eecavanna what kind of help do you need?  
I'm moving this to the next sprint as it appears to be active

@emileyfadrosh FYI

**Comment by eecavanna** [comment] 2024-02-24 01:15
The only **remaining question** I have is:

The PR description lists the following menu items:
1. Partner with us > Events
2. News & Impact > Newsletters

The "Events" menu item links to https://microbiomedata.org/events/. That is the page where I had been planning to add a section that contains links to past newsletters. That plan might have been a result of me making an incorrect assumption at some point.

What do you want the "Newsletters" menu item to link to?

**Comment by emileyfadrosh** [comment] 2024-02-24 05:25
Sorry for the confusion! 

1. Partner with us > Events: I believe this was meant to be a **new page** where we would maintain a calendar of upcoming events, but this has not been created. I can create a placeholder page, @jkelliher-github would that be OK? It should not link to the current events page since those are previous blog posts (https://microbiomedata.org/events/)
2. News & Impact > Newsletters: This would be a **new** page with the mailchimp postings. I think this was what you had in your development environment? 
3. News & Impact > Press Room: this should link to https://microbiomedata.org/events/ and not https://microbiomedata.org/media/

**Comment by eecavanna** [comment] 2024-03-07 05:36
Hi @emileyfadrosh and @jkelliher-github, I'm trying to tie up loose ends related to the website updates. For item 1 above, are either of you planning to create that page this Thursday or Friday? 

If not (which is OK with me), I think I'll create a separate ticket—specific to that task—and then close this one once I finish item 2.

**Comment by eecavanna** [comment] 2024-03-08 06:19
Hi @emileyfadrosh, thanks for creating that page for item 2. I added the newsletter archive and the sign-up form to the page. Here's what the result (which is currently live) look like.

![microbiomedata org_newsletters_compressed](https://github.com/microbiomedata/issues/assets/134325062/bfd767f0-14d6-487c-b1cb-0508a36c4765)

- I'll file an issue about that misaligned "Sign up for updates" button.

> I can add more to it afterwards, will that work for you?

Yes, you can continue to edit the page. As long as the "Newsletter Archive" and "Subscribe" blocks remain in the page's layout (on the "Edit page" page), the respective sections will appear on the user-facing page.

![image](https://github.com/microbiomedata/issues/assets/134325062/bf4ccb69-543f-45f4-b2a8-6b19f5170018)

I consider item 2 to be done at this point.

Next steps (from my perspective):

- I will create a ticket for item 1. I'll assign it to you and `jkelliher` for starters.
- I will create a ticket for adding a "Newsletters" menu item to "News & Impact" section of the top navigation bar, as originally specified in this ticket. Although the destination page now exists, I didn't want to add the menu item until I confirmed with you that you're OK with me adding it already.
- I will close this ticket.

**Closed** 2024-03-08 06:34 UTC
Labels: help wanted, question, X SMALL
