### ISSUE TITLE
Submission Context: Spell out project types & add links

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#105] opened 2023-03-02 21:36 UTC
CSP: Community Science Program
BERSS: Biological and Environmental Research Support Science - https://jgi.doe.gov/user-programs/other-programs/
FICUS: Facilities Integrating Collaborations for User Science
MONet: Molecular Observation Network
BRCSs: Bioenergy Research Centers - https://jgi.doe.gov/user-programs/other-programs/
@mslarae13 @emileyfadrosh can you provide the official links to the above project types?  Also double check that they are correct.

**Comment by pkalita-lbl** [comment] 2023-03-03 22:16
Closing as a duplicate of #104

**Closed by pkalita-lbl** 2023-03-03 22:16 UTC
