### ISSUE TITLE
Run nmdc workflows on NEON soil samples

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#264] opened 2023-05-26 21:47 UTC
**Deliverable this task is associated with**

_See Deliverables tab here: https://docs.google.com/spreadsheets/d/1jF1RU_TwQlJpqvHnKk-KieE6VlUv0je4eFddK9idPuE/edit?usp=sharing_

- 1

**RACI**

_Tag people in their roles_
- Responsible: @Michal-Babins, @mflynn-lanl 
- Accountable: @hubin-keio, @aclum 
- Consulted: @aclum @scanon 
- Informed:

**Describe the the task?**
- [x] stage seq data from NEON (~1400)
- [x] stage analyzed workflow data from JGI (~100) Gs0161344
- [x] Run complete workflow on seq data directly from NEON using 2023 version of img-nr for annotation (~1400)
- [x] Run reads based analysis, annotation, and binning on JGI data using 2023 version of img-nr for annotation (~100)
- [ ] check and debug failures

**Criteria for completion**
- Data objects that are output of workflow activity records are in mong prod for NEON soil samples

**Estimate people time**

**Completion Date (Goal)**
- Sept 8
*It is expected that some workflow runs may extend past this date, start time for workflow runs can't be moved up b/c of upstream dependencies 

**Target Sprint Start & End Dates**
- Start: July 3
- End: Sept 8

**Tag Blocker/Contingent upon issues**
Depends on https://github.com/microbiomedata/mg_annotation/issues/16
Depends on https://github.com/microbiomedata/nmdc_automation/issues/6

**Comment by aclum** [comment] 2023-06-08 17:26
@mflynn-lanl  We can at least start staging the JGI data once your tests complete.

**Comment by ssarrafan** [comment] 2023-07-13 21:27
@mflynn-lanl any updates on this for this sprint? 
will move to next sprint per the date due of 7/21/23

**Comment by aclum** [comment] 2023-07-14 21:40
I believe the data was staged.

**Comment by ssarrafan** [comment] 2023-07-28 22:44
I believe this is in progress. Moving to the next sprint. @Michal-Babins @aclum

**Comment by ssarrafan** [comment] 2023-08-10 21:29
I don't think all of the analysis was done before ESA. Will move to the backlog to add to a future sprint.
@aclum @Michal-Babins

**Comment by Michal-Babins** [comment] 2023-08-10 21:30
Hey @ssarrafan, that's right it was frozen for what was done up to that point, but the processing is still in progress.

**Comment by aclum** [comment] 2023-08-14 22:56
@Michal-Babins  @scanon can we get the rest of the data for the soil NEON samples processed this sprint? How much processing is left to go?

**Comment by Michal-Babins** [comment] 2023-08-15 13:50
@aclum I think we can get close if not finish. I have been letting them run in the background. I think I have maybe submitted 600. I have been running into issues with cromwell crashing over and over the past few days which has slowed things down and perlmutter will be down tomorrow. Let me touch base with @scanon and see how much we can scale.

**Comment by aclum** [comment] 2023-08-15 22:41
Per the workflows meeting we'll work on getting these run for the data sequenced outside of JGI processed this sprint.

**Comment by Michal-Babins** [comment] 2023-08-21 17:21
While attempting to retrieve data from https://data.microbiomedata.org/, the system encountered a "504 Gateway Time-out" error. I tried this a few times and I'm getting the same. Looks like originally encountered on Friday. All jobs submitted last week have not been able to complete end-to-end for this reason. Depending on when it is resolve and how long it will take to restart the failed jobs, may have to move to next sprint.

**Comment by ssarrafan** [comment] 2023-08-21 19:25
> While attempting to retrieve data from https://data.microbiomedata.org/, the system encountered a "504 Gateway Time-out" error. I tried this a few times and I'm getting the same. Looks like originally encountered on Friday. All jobs submitted last week have not been able to complete end-to-end for this reason. Depending on when it is resolve and how long it will take to restart the failed jobs, may have to move to next sprint.

@Michal-Babins is this resolved after Shane's restart today?

**Comment by Michal-Babins** [comment] 2023-08-21 19:48
I will have to see. I just resubmitted them and will see if they get picked up and processed by cromwell. However this was ~200 failures that have to be resubmitted.

**Comment by Michal-Babins** [comment] 2023-08-21 23:16
Looks to be going well so far.

**Comment by ssarrafan** [comment] 2023-08-25 17:20
@Michal-Babins will this be done today?  Should it be moved to the next sprint?

**Comment by aclum** [comment] 2023-08-25 23:39
Michal has had trouble getting the NERSC reservation approved so has been unable to process a large number of samples so this work will continue into the sprint starting August 28th. 

@Michal-Babins The omics_processing set records for the NEON soil samples from JGI are ready to import the workflow data. We need to import the filtering and assembly results as they are and run annotation w/5.2, binning, and the reads based taxonomy analysis so they match the rest of the study.

**Comment by Michal-Babins** [comment] 2023-08-28 13:44
@aclum, is there a mapping file for nmdc to jgi ga id?

**Comment by Michal-Babins** [comment] 2023-08-28 18:40
@aclum, @scanon looks like quota boost is in place and workflows are up and running. Iris still shows that HPSS is over quota, not sure who to contact to change this.

**Comment by aclum** [comment] 2023-08-28 22:00
@shreddd  is dealing w/the HPSS quota.

**Comment by Michal-Babins** [comment] 2023-08-29 15:19
I am having issues getting the workflows running. I was able to restart the workflows yesterday after the scratch quota was boosted, and everything was running okay. Today, I see that those jobs have all crashed. When I look I see that they are all failing to fetch the data:

Resolving data.microbiomedata.org (data.microbiomedata.org)... 128.55.206.112, 128.55.206.111, 128.55.206.106, ...
Connecting to data.microbiomedata.org (data.microbiomedata.org)|128.55.206.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-08-29 07:40:46 ERROR 404: Not Found.

This is now the 4th major cause of multiple workflow failures in a span of 1.5 weeks.

**Comment by shreddd** [comment] 2023-08-29 17:42
Quick update - HPSS quota shouldn't impact anything else (that is an internal soft quota thing). This is now fixed - basically during a backup we will go over briefly, before we clean up the old versions.

**Comment by shreddd** [comment] 2023-08-29 17:42
@Michal-Babins - is this stlll an issue? Could you include a sample URL that is failing?

**Comment by Michal-Babins** [comment] 2023-08-29 17:56
This is no longer an issue. The front end was recycled and the 404 issues are no longer and issue.

**Comment by shreddd** [comment] 2023-08-29 18:01
OK - I think there is a deeper issue with how the frontend internally proxies things to the data container. Will discuss with Kitware and open an issue if needed.

**Comment by aclum** [comment] 2023-08-30 17:40
There is one project missing from JDP, Ga0597026. I've filed a jira ticket with JGI.

**Comment by aclum** [comment] 2023-09-01 18:16
https://github.com/microbiomedata/nmdc_automation/issues/20 needs to be addressed before JGI workflow data can be ingested.

**Comment by aclum** [comment] 2023-09-06 17:49
Ga0597026 is now on JDP

**Comment by aclum** [comment] 2023-09-08 00:54
Workflows have been running @Michal-Babins  to add info on how much is outstanding. Moving to next sprint b/c of the JGI data ingest bug.

**Comment by Michal-Babins** [comment] 2023-09-08 14:29
All of the Neon data not in JGI has been submitted and processed. I see ~1300 that have successfully completed from readsQC to MAGs. I have not had time to cross check failed runs. It may be due to data quality, this is something I will have to do next week. 

For the data in JGI, I am still waiting for the right files to be downloaded to nersc. I know Mark has initiated the file transfer.

**Comment by aclum** [comment] 2023-09-22 23:34
JGI files have been ingested, re-annotation had issues due to cromwell connection issues, scratch quota issues and scratch file system issues so moving to the next sprint. I believe Michal also still needs to cross check failed runs

**Comment by aclum** [comment] 2023-10-06 20:53
re-annotations had finished and binning was running. Moving to the next sprint.

**Comment by Michal-Babins** [comment] 2023-10-17 15:06
Binning should be all finished. All that's left is to look at failures.

**Comment by aclum** [comment] 2023-10-21 00:22
Here are some failures Marcel found, not exhaustive.

NMDC_ID                            AP_ID                ERROR                                                                                                               NOTES
nmdc:omprc-11-3ccpc003  Ga0614120       /global/cfs/cdirs/m3408/results/nmdc:omprc-11-3ccpc003/ is not a directory!     N/A
nmdc:omprc-11-5db5cn15  Ga0614169       No assembly dir found in /global/cfs/cdirs/m3408/results/nmdc:omprc-11-5db5cn15/!       N/A
nmdc:omprc-11-6z6kan67  Ga0614105       No assembly dir found in /global/cfs/cdirs/m3408/results/nmdc:omprc-11-6z6kan67/!       N/A
nmdc:omprc-11-8nq16k21  Ga0614182       /global/cfs/cdirs/m3408/results/nmdc:omprc-11-8nq16k21/ is not a directory!     N/A
nmdc:omprc-11-dcsqme84  Ga0614181       /global/cfs/cdirs/m3408/results/nmdc:omprc-11-dcsqme84/ is not a directory!     N/A
nmdc:omprc-11-ka64by17  Ga0614183       /global/cfs/cdirs/m3408/results/nmdc:omprc-11-ka64by17/ is not a directory!     N/A
nmdc:omprc-11-p8dwzv82  Ga0614142       /global/cfs/cdirs/m3408/results/nmdc:omprc-11-p8dwzv82/ is not a directory!     N/A
nmdc:omprc-11-r04b2133  Ga0614107       /global/cfs/cdirs/m3408/results/nmdc:omprc-11-r04b2133/ is not a directory!     N/A
nmdc:omprc-11-w5b60h38  Ga0614171       /global/cfs/cdirs/m3408/results/nmdc:omprc-11-w5b60h38/ is not a directory!     N/A
nmdc:omprc-11-xs0rw715  Ga0614184       /global/cfs/cdirs/m3408/results/nmdc:omprc-11-xs0rw715/ is not a directory!     N/A
nmdc:omprc-11-ygpgrx75  Ga0614102       No assembly dir found in /global/cfs/cdirs/m3408/results/nmdc:omprc-11-ygpgrx75/!       N/A
nmdc:omprc-11-z1258154  Ga0614108       /global/cfs/cdirs/m3408/results/nmdc:omprc-11-z1258154/ is not a directory!     N/A

**Comment by Michal-Babins** [comment] 2023-10-26 14:48
I was able to do some deeper digging yesterday and found that through the wave of perlmutter outages a bunch of writes had failed or the file system was down but cromwell was still running. This lead to records and jobs going untracked. I have reset all of the neon records not accounted for. Will need to track the state of cromwell since whenever it goes down it creates a lot of problems between reads and writes on multiple fronts.

**Comment by hubin-keio** [comment] 2023-10-26 15:41
Thanks, Michal. This is a very important issue. We will need a mechanism that monitors the health of the file system (probably already available from NERSC) and tell Cromwell to resume workflow execution from the last time the file system is healthy (do not exist today). I believe Cromwell has support for resuming workflow execution through its API. We need bridge these two.

Bin

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Michal Babinski ***@***.***>
Sent: Thursday, October 26, 2023 10:48:11 AM
To: microbiomedata/issues ***@***.***>
Cc: Hu, Bin ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [microbiomedata/issues] Run nmdc workflows on NEON soil samples (Issue #264)


I was able to do some deeper digging yesterday and found that through the wave of perlmutter outages a bunch of writes had failed or the file system was down but cromwell was still running. This lead to records and jobs going untracked. I have reset all of the neon records not accounted for. Will need to track the state of cromwell since whenever it goes down it creates a lot of problems between reads and writes on multiple fronts.

**Comment by aclum** [comment] 2023-10-26 17:14
@Michal-Babins  @hubin-keio  we should discuss how much effort to put in here vs switching to jaws where there are 'jaws health' commands built in or see if we can reuse some jaws code.

**Comment by Michal-Babins** [comment] 2023-10-26 17:16
I don't think the switch would be too much effort on the automation side. All the worklfows need to be v1.0.0 wdl. We would just need to find a time where we are not running or processing things for 2 weeks.

**Comment by aclum** [comment] 2023-11-03 20:05
@Michal-Babins are you still debugging failures or this is ready to close?

**Comment by Michal-Babins** [comment] 2023-11-03 20:46
I have resubmitted them all and a few are finishing are running still. I would like to do another round of maintenance to find if there is anything unexpected. Keep it open until I've confirmed everything.

**Comment by Michal-Babins** [comment] 2023-11-17 18:45
Moving this to in review for now. I think how automation handles errors will play into this, I don't know if we want to keep this ticket open or break it down.

**Comment by ssarrafan** [comment] 2023-11-17 20:47
@Michal-Babins if you can break it down that would be great.  I'll move this to the next sprint to be reviewed and hopefully broken down into smaller issues.

**Comment by ssarrafan** [comment] 2023-12-01 21:48
@Michal-Babins @hubin-keio @aclum  this issue has been open since May and no updates for the last 2 weeks so I'm removing this from the sprint and adding the backlog label to it.  It's too bad because I think the work is mostly done right?  

If this will be actively addressed next sprint please add it to the new board.

**Closed** 2023-12-01 22:38 UTC
Labels: backlog
