### ISSUE TITLE
Milestone - Add visualizations that combine multi-omics data for analysis (4.5)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#507] opened 2023-10-06 22:42 UTC
Data Portal visualizations and custom data exploration
The Data Portal currently displays visualizations to guide the user to samples of interest. These
visualizations were created due to input for the scientific community around novel ways to interact with
data. Further developing these visualizations will differentiate the NMDC from other similar platforms
while showing the community that we listen to their requests. These visualizations include a map view,
distributions of sample collection dates and processing types, samples with paired multi-omics data, and
a view for organizing samples by environment. These summary views will be supplemented by new
visualizations exposing more details of the underlying processed omics data (Data Portal, Milestone 4.5
& 4.6). 

Page 36

see #508

**Comment by aclum** [comment] 2024-08-09 18:28
Duplicate of #508

**Closed by aclum** 2024-08-09 18:28 UTC
