### ISSUE TITLE
NMDC data portal still says pilot 

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/issues#100] opened 2023-03-01 20:03 UTC
This might just be my computer, but wanted to check...

If it isn't, can we update this?
![Screen Shot 2023-03-01 at 12 02 32 PM](https://user-images.githubusercontent.com/44581429/222253205-de8d1f2c-7cac-4d4c-86e3-f5add2f35ad2.png)

**Comment by naglepuff** [comment] 2023-04-27 20:51
Duplicate of microbiomedata/nmdc-server#958

Closing in favor of microbiomedata/nmdc-server#958, since that's in the nmdc-server repo.

**Closed by naglepuff** 2023-04-27 20:51 UTC
