### ISSUE TITLE
Metadata: Soil Environmental terms appear in all packages

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#111] opened 2023-03-02 22:06 UTC
See screenshot and description below.  Elevation shouldn't be required for water package.  

_couldn't replicate
will check again with @aclum_  Alicia showed me through screen share and we got a screenshot

**Comment by aclum** [comment] 2023-03-06 17:24
I believe the issue here was that for the water package elevation was showing up as required. @mslarae13

**Comment by aclum** [comment] 2023-03-14 23:30
This issue can be reproduced by selecting JGI metagenomes and a environmental package of water. Elevation shows up in yellow, a required field color. Cross referencing with MIxS this is not a required field.
https://genomicsstandardsconsortium.github.io/mixs/WaterMIMS/#direct

**Comment by ssarrafan** [comment] 2023-03-14 23:55
screenshot showing elevation as required in water package
<img width="1347" alt="elevationnoterequiredforwaterpackage" src="https://user-images.githubusercontent.com/79225425/225167661-7c354e5b-98e6-444f-938b-6100dfd9ee79.png">

**Comment by pkalita-lbl** [comment] 2023-03-16 21:07
@aclum The title of this issue references "soil environmental terms". Is this just about elevation? Are there other columns that should also not be required when the environment is not soil?

**Comment by aclum** [comment] 2023-03-16 21:30
"collection date" is recommended, not required by mixs for the water package and "sample storage temperature" is not required but I'm not sure how our requirements differ from MIxS. @turbomam  or @mslarae13  may be able to provide more information.  Elevation was the only term we talked about when doing the submission portal testing.

**Comment by turbomam** [comment] 2023-03-22 16:19
I have soil and water interfaces defined in the submission schema now. I can modify them according to the group consensus if clear guidance is provided, like "elevation should be allowed for the water interface but not required" or "elevation should not be associated with the water interface at all". 

It will be helpful to have stakeholders test these interfaces. That's possible now for anyone who has https://github.com/microbiomedata/submission-schema checked out into an appropriate development environment. @pkalita-lbl  and I can help others use this most direct approach.

We also have an issue to [expose these DH interfaces though GH pages](https://github.com/microbiomedata/submission-schema/issues/43), so the testers won't need a development environment.

We have been generating a report of all slot attributes for a environmental package classes, but have not been checking it into the repo. I will either start checking it in or at least link the most recent one here.

**Comment by turbomam** [comment] 2023-03-22 16:28
NMDC team members can also provide examples of data that they think should be valid or invalid in https://github.com/microbiomedata/submission-schema/tree/main/src/data

**Comment by turbomam** [comment] 2023-03-22 22:42
> @turbomam Do you want me to make an example valid water submission as an acceptance criteria test or this has been done already?

We already have several sample data files in https://github.com/microbiomedata/submission-schema/tree/main/src/data, including
- minimal but valid
- exhaustive valid
  - These are exhaustive in a good faith sense. I I don't have any proof right now that they include every slot available for any given class.
- invlid
  - These are minimal by design. Each should only contain one invalid attribute.

Having said that, you are welcome to add more valid or invalid files. I think the invalid ones are actually more useful at this point.

**Comment by pkalita-lbl** [comment] 2023-03-24 21:45
I think we might just be able to close this one. The latest version of the submission schema already has the `required` attribute removed from the `elev` slot in the water template. 

It doesn't show up that way in the submission portal yet because we need to make a new release of the submission schema with that change in it and bring it into the submission portal. But that's sort of a separate piece of work that's already on my plate.

**Closed by pkalita-lbl** 2023-03-24 21:45 UTC
