### ISSUE TITLE
submission portal remove row and add row above features not working

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#82] opened 2023-02-17 21:14 UTC
I was testing the dev version of the submission portal using chrome today and noticed that on the bottom left the options to 'remove row' and 'add row above' do no work properly when entering sample metadata.

cc @mslarae13

**Comment by mslarae13** [comment] 2024-03-25 19:16
The "add # of rows to the bottom" seems to be working for me

The remove row and add row above seems to be gone.
@naglepuff do you remember implementing this change?

**Comment by naglepuff** [comment] 2024-03-25 20:50
This might be a data harmonizer question (@pkalita-lbl does this sound familiar?)

As far as I can tell, we just use the [DH package to create the footer](https://github.com/microbiomedata/nmdc-server/blob/d1a0bb532aeec8781511c4af6ffcc7ee2bbb7773/web/src/views/SubmissionPortal/harmonizerApi.ts#L203). It doesn't look like any code related to the footer has been touched in quite some time.

**Comment by aclum** [comment] 2024-03-25 21:36
The remove row and add row above options rarely show up under the 'go to previous step' button on the bottom left. I had it happen briefly today but then it went away and it did not appear to work when I clicked on one of those options.

**Comment by pkalita-lbl** [comment] 2024-03-26 15:47
Are we talking about these? 

![image](https://github.com/microbiomedata/issues/assets/102547565/9f310f13-cf41-4303-b29a-a977e0b16a0f)

Or this?

![image](https://github.com/microbiomedata/issues/assets/102547565/7e94b40b-c276-4f51-99f7-d2fdc3b0bc3d)

**Comment by aclum** [comment] 2024-03-26 20:17
@pkalita-lbl the first image, the remove row, insert row above, insert row below features.

**Comment by pkalita-lbl** [comment] 2024-03-26 20:29
I'm surprised you even saw those down there! I'm _not_ surprised they're not working. Those are supposed to be presented in a little context menu when right click. Like so:

<img width="318" alt="image" src="https://github.com/microbiomedata/issues/assets/102547565/b7b42fe5-73ff-4db2-96c1-7a4d9b575811">

So, I don't know. All I can say is that is functionality that's provided via DataHarmonizer. But obviously something about the way we're embedded the DH instance on the page has them all kinds of broken. I don't know any more off the top of my head. Needs investigation.

**Comment by mslarae13** [comment] 2024-03-29 17:24
I'm confused.. Why can't i see those? (the 1st)

There are no options below "Previous Step" for me

**Comment by pkalita-lbl** [comment] 2024-03-29 18:06
They'd likely only be there if you right click on a row number. But regardless you're not missing much because 1) they don't work and 2) they shouldn't be down there in the first place. 

We should test it once it's on dev, but I think the library upgrades in https://github.com/microbiomedata/nmdc-server/pull/1191 might fix this.

**Comment by pkalita-lbl** [comment] 2024-04-05 23:25
Duplicate of https://github.com/microbiomedata/nmdc-server/issues/1001?

See https://github.com/microbiomedata/nmdc-server/issues/1001#issuecomment-2040758902

**Closed** 2024-04-08 19:38 UTC
