### ISSUE TITLE
NEON - soil metagenome individual samples sequenced 

### ISSUE THREAD

**Issue by aclum** [microbiomedata/issues#432] opened 2023-09-18 21:01 UTC
**Deliverable this task is associated with**

_See Deliverables tab here:_

- 1

**RACI**

_Tag people in their roles_
- Responsible: @sujaypatil96 
- Accountable: @turbomam  @aclum 
- Consulted:
- Informed:

**Describe the the task**
- [ ] We are missing extraction_set, library_construction, and omics_processing_set records for some samples which were sequenced both as a composite and as an individual sample. The current data in mongo captures the composite sample correctly and the biosample_set record is correct but is missing the other classes. An example is biosample id nmdc:bsm-11-hzeya107, name nmdc:bsm-11-hzeya107.   see https://github.com/microbiomedata/issues/issues/422 for details

**Criteria for completion**
- Two omics_processing_set records tracking back to biosample_set id nmdc:bsm-11-hzeya107

**Estimate people time**
-  1 person, 8 hours

**Completion Date (Goal)**
- Feb 9, 2024

**Target Sprint Start & End Dates**
- Start: January 15, 2024
- End: Febuary 9, 2024

**Tag Blocker/Contingent upon issues**

**Comment by aclum** [comment] 2024-01-23 23:14
Adding this to the sprint b/c Sujay finished the surface water work.

**Comment by ssarrafan** [comment] 2024-01-26 22:25
Moving to next sprint. @aclum @sujaypatil96

**Comment by sujaypatil96** [comment] 2024-02-02 02:47
How do we write a query to get a list of all individual samples?

**Comment by aclum** [comment] 2024-02-03 00:30
Check for records where the NEON's `mms_metagenomeDnaExtraction.dnaSampleID` is not the `name` of a NMDC `processed_sample_set` document and the `mms_metagenomeDnaExtraction.sequenceAnalysisType` equals ( `marker gene and metagenomics` OR `metagenomics`)

**Comment by sujaypatil96** [comment] 2024-02-09 19:32
This issue needs to be moved to the next sprint.

**Comment by sujaypatil96** [comment] 2024-02-16 18:22
> Check for records where the NEON's `mms_metagenomeDnaExtraction.dnaSampleID` is not the `name` of a NMDC `processed_sample_set` document and the `mms_metagenomeDnaExtraction.sequenceAnalysisType` equals ( `marker gene and metagenomics` OR `metagenomics`)

I still don't think I fully follow this @aclum. I generated a list by getting a list of all the _dnaSampleID_ values from a combined `mms_metagenomeDnaExtraction` table (from NEON) and checking which _dnaSampleID_ from that list is/is not in `processed_sample_set`. Here is that list: [neon_soil_individual_sample_dnaSampleID.txt](https://github.com/microbiomedata/issues/files/14314631/neon_soil_individual_sample_dnaSampleID.txt)

**Comment by sujaypatil96** [comment] 2024-02-16 18:35
According to the documentation (NEON_metagenomes_userGuide_vE.pdf):

> The individual samples used to generate the pooled metagenomics samples are found as a pipe‐delimited string in the field **_genomicsPooledIDList_** located in the data table **_sls_metagenomicsPooling_**, which is part of the Soil Physical Properties (distributed periodic) data product (DP1.10086).

There are no extraction, library preparation, omics processing records associated with any "individual" biosamples that are part of pooling processes?

**Comment by aclum** [comment] 2024-02-20 20:35
discussed over slack as well, this list pulls in samples which have got through pooling. Updated requirements are below:

join on mms_metagenomeSequencing.dnaSampleID=mms_metagenomeDnaExtraction.dnaSampleID, join mms_metagenomeDnaExtraction.genomicsSampleID=sls_metagenomicsPooling.genomicsSampleID. If a dnaSampleID in mms_metagenomeSequencing does not track back to a record from the pooling table we need to generate the missing records. To do this join mms_metagenomeSequencing.dnaSampleID=mms_metagenomeDnaExtraction.dnaSampleID to get mms_metagenomeDnaExtraction.genomicsSampleID, join mms_metagenomeDnaExtraction.genomicsSampleID=sls_soilCoreCollection.geneticSampleID to get sls_soilCoreCollection.sampleID. Use sls_soilCoreCollection.sampleID=nmdc.biosampel_set.name to get the NMDC biosample ID. This NMDC ID is has_input to an extraction_set record, which generates a processed sample, which is has_input to library_preparation, which generates a processed sample which is has_input to the omics_processing_set record which has_output data objects

**Comment by aclum** [comment] 2024-02-20 20:35
discussed over slack as well, this list pulls in samples which have got through pooling. Updated requirements are below:

join on mms_metagenomeSequencing.dnaSampleID=mms_metagenomeDnaExtraction.dnaSampleID, join mms_metagenomeDnaExtraction.genomicsSampleID=sls_metagenomicsPooling.genomicsSampleID. If a dnaSampleID in mms_metagenomeSequencing does not track back to a record from the pooling table we need to generate the missing records. To do this join mms_metagenomeSequencing.dnaSampleID=mms_metagenomeDnaExtraction.dnaSampleID to get mms_metagenomeDnaExtraction.genomicsSampleID, join mms_metagenomeDnaExtraction.genomicsSampleID=sls_soilCoreCollection.geneticSampleID to get sls_soilCoreCollection.sampleID. Use sls_soilCoreCollection.sampleID=nmdc.biosampel_set.name to get the NMDC biosample ID. This NMDC ID is has_input to an extraction_set record, which generates a processed sample, which is has_input to library_preparation, which generates a processed sample which is has_input to the omics_processing_set record which has_output data objects

**Comment by sujaypatil96** [comment] 2024-02-22 00:05
@ssarrafan needs to be moved to next sprint, it will not be complete by 2/23.

**Comment by ssarrafan** [comment] 2024-02-22 22:44
Moving another one to the next sprint @aclum

**Comment by sujaypatil96** [comment] 2024-02-27 00:48
The records that need to be fixed for the 1000 soils study:

Individual samples that have already been ingested into NMDC mongo (create Extraction, LibraryPreparation, OmicsProcessing) - [individual_samples_in_db.csv](https://github.com/microbiomedata/issues/files/14412872/individual_samples_in_db.csv)
Individual samples that haven't been ingested into NMDC mongo yet (create Biosample and downstream records for these) - [individual_samples_not_in_db.csv](https://github.com/microbiomedata/issues/files/14412873/individual_samples_not_in_db.csv)

**Comment by aclum** [comment] 2024-03-01 22:38
@sujaypatil96  Can you check the logic, `ABBY_004-M-20170605-COMP` should not be in either of these lists and it is listed in [individual_samples_not_in_db.csv](https://github.com/microbiomedata/issues/files/14412873/individual_samples_not_in_db.csv). That is a composite sample. You can find that name in NEON.D16.ABBY.DP1.10086.001.sls_metagenomicsPooling.2017-06.*.csv and is a pool of these three biosamples `ABBY_004-M-12-34-20170605|ABBY_004-M-32-14.5-20170605|ABBY_004-M-0.5-8-20170605`

**Comment by sujaypatil96** [comment] 2024-03-05 20:36
@aclum `ABBY_004-M-20170605-COMP` is a weird one that stayed in because we didn't apply post-query record removal/filtering logic (for ex. full duplicate removal). If you look at that row it doesn't even have a `sampleID` (Biosample `id`) associated with it, so we should be good to remove that.

**Comment by sujaypatil96** [comment] 2024-03-07 22:29
Here is the first JSON file with `Extraction`, `LibraryPreparation`, `OmicsProcessing` and `DataObject` records for biosamples that are are already in the database.
[neon_individual_samples_in_db.json](https://github.com/microbiomedata/issues/files/14530850/neon_individual_samples_in_db.json)

**Comment by sujaypatil96** [comment] 2024-03-07 22:31
I'm still working on making the JSON file for the second set of records, i.e., individual samples which do not have Biosample (and downstream) records in the database.

This issue will be ready to be closed once those two JSON files are ready, have been reviewed and submitted to Mongo.

**Comment by sujaypatil96** [comment] 2024-03-07 22:32
This issue will need to be moved to the next sprint @ssarrafan. I see it getting done in the first couple of days of the next sprint.

**Comment by sujaypatil96** [comment] 2024-03-11 23:52
Here is the JSON file that has been created for individual samples that are not in the database. We have created biosample, extraction, library preparation, omics processing and data object instances for these records.
[neon_individual_samples_not_in_db.json](https://github.com/microbiomedata/issues/files/14565520/neon_individual_samples_not_in_db.json)

**Comment by sujaypatil96** [comment] 2024-03-12 05:59
Both the JSON files linked in this issue have been submitted and ingested into Mongo (confirmed/verified by looking for these records in the database). I think this issue is ready to be closed @aclum.

**Closed** 2024-03-13 22:00 UTC
