### ISSUE TITLE
Create framework for validating MongoDB data

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/issues#266] opened 2023-06-02 23:15 UTC
Create a validation framework and tests in MongoDB to validate existing data for referential integrity, schema compliance, and ensuring that data is mapped correctly to files and other object.

@eecavanna add checklist of items here. 

---

### Functionality 

> This list is tentative. I expect it to change and grow over time.

- [ ] **Referential integrity (documents by ID)**: Given a document in a MongoDB database, check whether every document it references [exists](https://www.mongodb.com/docs/manual/reference/method/db.collection.findOne/) in the database
- [ ] **Referential integrity (files by URL)**: Given a document in a MongoDB database, check whether every file URL it references can be [accessed](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) via the public Internet
- [ ] **Schema compliance**: Given a document in a MongoDB database, check whether it [complies](https://www.mongodb.com/docs/manual/core/schema-validation/) with the [NMDC schema](https://github.com/microbiomedata/nmdc-schema) (see [this tutorial in nmdc-runtime](https://github.com/microbiomedata/nmdc-runtime/blob/main/docs/tutorials/json.md), and this example of a [validation function in nmdc-runtime](https://github.com/microbiomedata/nmdc-runtime/blob/main/metadata-translation/src/bin/validate_json.py), and the `validate_json` function [here in nmdc-runtime](https://github.com/microbiomedata/nmdc-runtime/blob/main/nmdc_runtime/util.py))

**Comment by eecavanna** [comment] 2023-06-09 23:03
### Functionality 

> This list is tentative. I expect it to change and grow over time.

- [ ] **Referential integrity (documents by ID)**: Given a document in a MongoDB database, check whether every document it references exists
- [ ] **Referential integrity (files by URL)**: Given a document in a MongoDB database, check whether every file URL it references is accessible from the public Internet

**Comment by eecavanna** [comment] 2023-06-16 19:11
### Sprint 12 - end of sprint update:
- I configured my SSH client and MongoDB GUIs to access the "development" and "production" databases
- I documented the configuration processes for future reference (in an "internal" GitHub repository)
- I learned from a teammate (Mark) about schema compliance validation (i.e. LinkML-based and jsonschema-based)
- I completed the first 75% of the [Master the MongoDB Aggregation Pipeline](https://www.linkedin.com/learning/master-the-mongodb-aggregation-pipeline) course on LinkedIn Learning
- I got experience querying the database via Python (this was part of a different task, but the experience is applicable)

**Comment by ssarrafan** [comment] 2023-06-30 17:28
@eecavanna should this continue to the next sprint? Will you be doing another end of sprint update?

**Comment by eecavanna** [comment] 2023-06-30 18:18
Hi @ssarrafan, yes, I'll move it to the next sprint.

### Sprint 13 - end of sprint update:

- I made a plan with @shreddd: I will begin by implementing validation in a Jupyter notebook (Python), work out the kinks there, then pursue incorporating that functionality into `nmdc-runtime`

**Comment by ssarrafan** [comment] 2023-07-13 21:28
@eecavanna any update on this for sprint 14?  are you planning to continue to work on this actively?

**Comment by eecavanna** [comment] 2023-07-14 19:32
### Sprint 14 - end of sprint update:
- No update (no progress this sprint)

I do plan to continue (resume) working on this during the next sprint.

**Comment by ssarrafan** [comment] 2023-07-28 22:59
@eecavanna what's the status of this issue?

**Comment by eecavanna** [comment] 2023-07-28 23:27
@ssarrafan, I made some progress on it during this sprint, and I will continue working on it next sprint.

### Sprint 15 - end of sprint update:
- Explored JSON Schema-based validation at database level and application level
    - Database level: MongoDB has a "[find all documents that violate this JSON Schema](https://www.mongodb.com/docs/manual/core/schema-validation/use-json-schema-query-conditions/#find-documents-that-don-t-match-the-schema)" feature
        - **Pros:** 
            - Does not require that data be transferred from the database to the application, since the query result "is" the validation result
        - **Cons:** 
            - That MongoDB feature does not support JSON Schemas containing the `$ref` key (which the `nmdc-schema` JSON Schema does contain), so I think this approach would involve—at the application level—recursively resolving all `$ref` values to the literal objects they reference, and then using the resulting `$ref`-less JSON Schema with that Mongo feature
            - I think that MongoDB feature only tells you which documents are invalid, but does not tell you any more details (e.g. which specific fields contain invalid values)
    - Application level: Python's `jsonschema` package has a [`validate`](https://python-jsonschema.readthedocs.io/en/stable/validate/#the-basics) function
        - **Pros:** 
            - It does support JSON Schemas containing the `$ref` key
            - It does tell you which specific fields contain invalid values
        - **Cons:** 
            - It would require that data be transferred from the database to the application, since validation would happen at the application level

**Comment by cmungall** [comment] 2023-08-02 21:08
This is great (I thought we were already doing a lot of this)

I would add: this should be the primary means of validating the contents of the NMDC data store. I recently discovered there is a secret method that depends on sqlalchemy in the data portal. Sometimes redundancy is good but we should not be dependent on mechanisms like this. There should be a single SOT for what consistutes the schema, and a single SOT for the primary data

**Comment by dwinston** [comment] 2023-08-04 18:55
@eecavanna perhaps we can do two-stage validation where the first stage uses fast, database-native validation to determine *that* a certain set of documents is invalid, and then uses slower, application-level validation (using full JSON Schema and LinkML logic, as in [`nmdc_runtime.util.validate_json`](https://github.com/microbiomedata/nmdc-runtime/blob/0909bb94c18d1a9decf538c2c6b76f800c8da359/nmdc_runtime/util.py#L444), to determine *why* they're invalid. This approach does not address referential integrity, as there will be false negatives from the database-native jsonschema validation, which doesn't check referential integrity.

**Comment by eecavanna** [comment] 2023-08-04 23:38
Hi @dwinston, I like the approach you are suggesting: start with the database-level validation; and only do the application-level validation if the former reports any violations. I am under the impression both JSON Schema and LinkML validation are necessary at this point, in which case, some application-level validation (i.e. the LinkML type) would be necessary; but the two-stage approach you are suggesting could still spare us from some unnecessary application-level JSON Schema validation.

I tried implementing database-level validation earlier this week, but ran into a low-level issue: The JSON Schema included in the `nmdc-schema` Python package uses the `$ref` key, and [that is one of several keys that has been omitted from MongoDB's support of JSON Schema](https://www.mongodb.com/docs/manual/reference/operator/query/jsonSchema/#omissions). After learning that, I tried using a Python package called [`referencing`](https://referencing.readthedocs.io/en/stable/api/) to "resolve" the `$ref` values to their literal values (I was planning to then pass that `$ref`-less JSON Schema to Mongo), but ran into enough issues on the way there that I decided to work on something else (I don't recall the issue I left off at, but I'm confident I would be able to reproduce it as I still have the code that did so). At that point, I switched my focus to application-level validation, since I figured I would eventually be working on that anyway in order to perform the LinkML validation.

Once I make some progress with application-level JSON Schema validation (which is what I'm working on now), I'll shift my focus back to database-level validation.

**Comment by ssarrafan** [comment] 2023-08-10 21:30
@eecavanna what's the status of this issue?  Should we break it down into smaller issues?

**Comment by ssarrafan** [comment] 2023-08-11 20:20
Assuming this is still active, moving to next sprint.  @eecavanna if you would like to break down into smaller issues let me know.

**Comment by eecavanna** [comment] 2023-08-11 20:32
Thanks, @ssarrafan. I do plan to break it up into smaller issues later today.

**Comment by eecavanna** [comment] 2023-08-11 22:59
I have broken this issue (ticket) up into the following smaller issues (tickets):
- #385
- #386 
- #387 
- #388 

I will close this issue now; since it is being represented by those other issues, which I will maintain instead.

**Closed by eecavanna** 2023-08-11 22:59 UTC
